# Generated by Django 4.0 on 2022-07-11 10:46

from django.db import migrations, models
import newsapp.Manager


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('objects', newsapp.Manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Логин'),
        ),
    ]
