# Generated by Django 4.0 on 2022-07-24 16:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0011_linearizes_history'),
        ('newsapp', '0002_alter_author_managers_alter_author_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshBlacklistedToken',
            fields=[
                ('blacklistedtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_blacklist.blacklistedtoken')),
            ],
            bases=('token_blacklist.blacklistedtoken',),
        ),
        migrations.CreateModel(
            name='RefreshOutstandingToken',
            fields=[
                ('outstandingtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_blacklist.outstandingtoken')),
            ],
            bases=('token_blacklist.outstandingtoken',),
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Публиковать'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(db_index=True, default='новая запись', max_length=150, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_text',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='context',
            field=ckeditor.fields.RichTextField(db_index=True, null=True, verbose_name='Краткое описание новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_add',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата создания ленты'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image1',
            field=models.ImageField(blank=True, db_index=True, upload_to='', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image3',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_news',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Главные новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='Наименования новости'),
        ),
    ]
